site_name: reNgine Documentation

# Theme
theme:
  name: material
  palette:
    scheme: default
    primary: blue
  font:
    text: Nunito Sans
    code: Roboto Mono

repo_url: https://github.com/yogeshojha/rengine

site_description: reNgine is an automated reconnaissance framework meant for information gathering during penetration testing of web applications. reNgine has customizable scan engines, which can be used to scan the websites, endpoints, and gather information.
site_author: Yogesh Ojha

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences

# Nav Bar
nav:
    - Home: 'index.md'
    - reNgine Installation:
        - Introduction: 'install/index.md'
        - Prerequisites: 'install/prerequisites.md'
        - Quick Install(Only Ubuntu): 'install/quick-install.md'
        - Detailed Installation Steps(Win/Mac): 'install/install.md'
        - Installing reNgine on VPS: 'install/vps-installation.md'
        - Run reNgine using remote Database: 'install/remotedb.md'
    - Using reNgine:
        - Introduction: 'usage/index.md'
        - Dark Mode: 'usage/dark.md'
        - Adding Targets: 'usage/targets.md'
        - Tagging Targets to an Organization: 'usage/test.md'
        - Scan Engines: 'usage/test.md'
        - Initiating Scan: 'usage/test.md'
        - Scheduling Scan: 'usage/test.md'
        - Wordlist: 'usage/test.md'
        - Interesting Lookup: 'usage/test.md'
        - Automatic Vulnerability Reporting to Hackerone: 'usage/test.md'
        - Settings:
              - Proxy Settings: 'usage/settings.md'
              - Tool Settings: 'usage/settings.md'
              - Notification Settings: 'usage/settings.md'
              - reNgine Settings: 'usage/settings.md'

    - Uninstalling reNgine: 'uninstall/index.md'
