site_name: reNgine
site_description: reNgine is an automated reconnaissance framework meant for information gathering during penetration testing of web applications. reNgine has customizable scan engines, which can be used to scan the websites, endpoints, and gather information.
site_author: Yogesh Ojha
repo_url: https://github.com/yogeshojha/rengine
site_url: https://reNgine.wiki

# Theme
theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en
  feature:
    tabs: false
  palette:
    primary: black
  favicon: static/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  logo: static/logo.png

copyright: "Copyright &copy; 2021 reNgine Author(s)"

# Options
extra:
  search:
    languages: "en"
  social:
    - icon: fontawesome/solid/globe-asia
      link: https://www.rengine.wiki/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yogeshojha
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ojhayogesh11

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences

# Nav Bar
nav:
    - Overview:
        - Introduction: 'index.md'
        - Community: 'community.md'
    - reNgine Installation:
        - Introduction: 'install/index.md'
        - Prerequisites: 'install/prerequisites.md'
        - Quick Install(Only Ubuntu): 'install/quick-install.md'
        - Detailed Installation Steps(Win/Mac): 'install/install.md'
        - Installing reNgine on VPS: 'install/vps-installation.md'
        - Run reNgine using remote Database: 'install/remotedb.md'
    - Updating reNgine: 'update/index.md'
    - Using reNgine:
        - Introduction: 'usage/index.md'
        - Dark Mode: 'usage/dark.md'
        - Adding Targets: 'usage/targets.md'
        - Scaning Target: 'usage/scan_target.md'
        - Tagging Targets to an Organization: 'usage/organization.md'
        - Scan Engines: 'usage/scan_engine.md'
        - Wordlist: 'usage/wordlist.md'
        - Interesting Subdomains Lookup: 'usage/interesting.md'
        - Automatic Vulnerability Reporting to Hackerone: 'usage/hackerone.md'
        - Settings:
              - reNgine Settings: 'usage/settings.md'
              - Proxy Settings: 'usage/proxy.md'
              - Tool Settings: 'usage/tool_conf.md'
              - Notification Settings: 'usage/notification.md'

    - Uninstalling reNgine: 'uninstall/index.md'
